### ISSUE TITLE
Impossibility to run fatJar on windows with double-click.

### ISSUE THREAD

**Issue by maxt** [alexeygusev78/LogAnalyzer#3]
It's impossible to run LogAnalyzer on windows by double-click. It happens because program requires -gui option for run.  It would be better if it runs in gui mode by default without any additional options. 

![fatjar](https://user-images.githubusercontent.com/298723/32885378-655702e6-cace-11e7-8a0d-d4c6e66cb3d3.png)

**Comment by alexeygusev78** [comment]
Fixed by maxt.
